# Generated by Django 5.0.3 on 2024-04-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_reader_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='librayrecords',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reader',
            name='date_of_birth',
            field=models.DateField(default='1999-09-25'),
            preserve_default=False,
        ),
    ]
