# Generated by Django 5.0.3 on 2024-04-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_librayrecords_status_alter_reader_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='awards',
            field=models.ManyToManyField(null=True, to='base.authoraward'),
        ),
    ]
