# Generated by Django 5.0.3 on 2024-04-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_author_awards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, to='base.authoraward'),
        ),
    ]
