# Generated by Django 5.0.3 on 2024-04-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_author_options_alter_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, to='base.bookaward'),
        ),
    ]
