# Generated by Django 5.0.3 on 2024-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_book_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateTimeField(default='1970-01-01', help_text='Enter the published date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Enter the publication company', max_length=250),
        ),
    ]
