# Generated by Django 5.0.3 on 2024-04-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_author_awards_alter_book_awards'),
    ]

    operations = [
        migrations.AddField(
            model_name='librayrecords',
            name='projected_date',
            field=models.DateField(null=True),
        ),
    ]
