# Generated by Django 5.0.3 on 2024-04-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_librayrecords_projected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librayrecords',
            name='return_status',
            field=models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], max_length=250, null=True),
        ),
    ]
