# Generated by Django 5.0.3 on 2024-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_book_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='book.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='reader',
            name='reader_image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='images/'),
        ),
    ]
